### PR TITLE
You could simplify your Reads instancies.

### PR DESCRIPTION
**Pull request by senia-psm**
Here is a couple of examples of `Reads` simplification.

### CODE REVIEW

**Comment by vooolll** [comment]
@senia-psm First of all I appreciate,   I agree about simplification, but unfortunately facebook don't use `ISO_DATE_TIME`(test fails), so I must format it using  `SimpleDateFormat`. Please get read of comment

**Comment by vooolll** [comment]
@senia-psm Actually I am not sure why should I avoid mixing of DSL-based and macros-based formats. I just use it where I don't have underscores, to keep code smaller.

**Comment by senia-psm** [comment]
Do they have `'T'` instead of `T` in format? Any way it would be better to use a custom `DateTimeFormatter` (in a private field) instead of `SimpleDateFormat`. I suppose there is not performance issue in this particular case, but recreating a `SimpleDateFormat` on each parsing is a "code smell".

**Comment by senia-psm** [comment]
> why should I avoid mixing of DSL-based and macros-based formats
There are 2 main options to create a `json` API with Play-json:
1. Using DTO classes. In this case API documentation is stored in a package with model classes.
2. Using DAO. In this case API documentation is stored in separate "json protocol" object.

In you case to get this documentation one have to take into account both places. It violates single responsibility principle.
In a bigger project you may confuse other developers. For instance: one might get an impression that you have a DSL-based formats and it is safe to rename fields in model classes.

**Comment by senia-psm** [comment]
>  delete comment in code, so I can merge this pull request

This PR is not a refactoring (there are other `Reads` to fix). It's more like review.
I'm not going to contribute to this project on a regular basis.
I just checked a couple of random files before the interview yesterday. By the way: why did you missed it?

**Comment by vooolll** [comment]
@senia-psm Facebook has plus or something in a format. Interview is on Wednesday. I think no idea why you write about dao and dto. There is a simpler words to call it, anyway. Thank you for your comments. And I don't want to attend interview today. Delete myself from your list of candidates, thank you.

**Comment by vooolll** [comment]
There is some different format used, not iso. About SimpleDateFormat yep , noticed no need to recreate it each time , it is bad. Mixin dsl based and maros format is not that bad, right it is inconsistent , but but not hard to figure out . I am sorry for interview. Thank you for your comments.

**Comment by vooolll** [comment]
@senia-psm according to format -  https://travis-ci.org/vooolll/facebook4s/jobs/299568338

**Pull request merged**
